volumes:
  home_node_modules:
  news_node_modules:
  shop_node_modules:
  travel_node_modules:
  dsp_node_modules:
  dsp_a_node_modules:
  dsp_b_node_modules:
  dsp_c_node_modules:
  dsp_d_node_modules:
  ssp_node_modules:
  ssp_top_node_modules:
  ssp_a_node_modules:
  ssp_b_node_modules:
  ssp_c_node_modules:
  ssp_d_node_modules:
  topics_node_modules:
  topics-server_node_modules:
  ad_server_node_modules:

services:
  home:
    image: gcr.io/privacy-sandbox-demos/home:latest
    build: ./services/home
    container_name: "sandcastle_home"
    hostname: ${HOME_HOST:?err}
    env_file:
      - .env
    networks:
      - adnetwork

  news:
    image: gcr.io/privacy-sandbox-demos/news:latest
    build: ./services/news
    container_name: "sandcastle_news"
    hostname: ${NEWS_HOST:?err}
    env_file:
      - .env
    volumes:
      - ./services/news:/workspace
      - news_node_modules:/workspace/node_modules
    networks:
      - adnetwork

  shop:
    image: gcr.io/privacy-sandbox-demos/shop:latest
    build: ./services/shop
    container_name: "sandcastle_shop"
    hostname: ${SHOP_HOST:?err}
    env_file:
      - .env
    volumes:
      - ./services/shop:/workspace
      - shop_node_modules:/workspace/node_modules
    networks:
      - adnetwork

  travel:
    image: gcr.io/privacy-sandbox-demos/travel:latest
    build: ./services/travel
    container_name: "sandcastle_travel"
    hostname: ${TRAVEL_HOST:?err}
    env_file:
      - .env
    volumes:
      - ./services/travel:/workspace
      - travel_node_modules:/workspace/node_modules
    networks:
      - adnetwork

  dsp:
    image: gcr.io/privacy-sandbox-demos/dsp:latest
    build: ./services/dsp
    container_name: "sandcastle_dsp"
    hostname: ${DSP_HOST:?err}
    env_file:
      - .env
    volumes:
      - ./services/dsp:/workspace
      - dsp_node_modules:/workspace/node_modules
    networks:
      - adnetwork

  dsp-a:
    image: gcr.io/privacy-sandbox-demos/dsp-a:latest
    build: ./services/dsp-a
    container_name: "sandcastle_dsp_a"
    hostname: ${DSP_A_HOST:?err}
    env_file:
      - .env
    volumes:
      - ./services/dsp-a:/workspace
      - dsp_a_node_modules:/workspace/node_modules
    networks:
      - adnetwork

  dsp-b:
    image: gcr.io/privacy-sandbox-demos/dsp-b:latest
    build: ./services/dsp-b
    container_name: "sandcastle_dsp_b"
    hostname: ${DSP_B_HOST:?err}
    env_file:
      - .env
    volumes:
      - ./services/dsp-b:/workspace
      - dsp_b_node_modules:/workspace/node_modules
    networks:
      - adnetwork
  
  dsp-c:
    image: gcr.io/privacy-sandbox-demos/dsp-c:latest
    build: ./services/dsp-c
    container_name: "sandcastle_dsp_c"
    hostname: ${DSP_C_HOST:?err}
    env_file:
      - .env
    volumes:
      - ./services/dsp-c:/workspace
      - dsp_c_node_modules:/workspace/node_modules
    networks:
      - adnetwork

  dsp-d:
    image: gcr.io/privacy-sandbox-demos/dsp-d:latest
    build: ./services/dsp-d
    container_name: "sandcastle_dsp_d"
    hostname: ${DSP_D_HOST:?err}
    env_file:
      - .env
    volumes:
      - ./services/dsp-d:/workspace
      - dsp_d_node_modules:/workspace/node_modules
    networks:
      - adnetwork

  ssp:
    image: gcr.io/privacy-sandbox-demos/ssp:latest
    build: ./services/ssp
    container_name: "sandcastle_ssp"
    hostname: ${SSP_HOST:?err}
    env_file:
      - .env
    volumes:
      - ./services/ssp:/workspace
      - ssp_node_modules:/workspace/node_modules
    networks:
      - adnetwork

  ssp-a:
    image: gcr.io/privacy-sandbox-demos/ssp-a:latest
    build: ./services/ssp-a
    container_name: "sandcastle_ssp_a"
    hostname: ${SSP_A_HOST:?err}
    env_file:
      - .env
    volumes:
      - ./services/ssp-a:/workspace
      - ssp_a_node_modules:/workspace/node_modules
    networks:
      - adnetwork

  ssp-b:
    image: gcr.io/privacy-sandbox-demos/ssp-b:latest
    build: ./services/ssp-b
    container_name: "sandcastle_ssp_b"
    hostname: ${SSP_B_HOST:?err}
    env_file:
      - .env
    volumes:
      - ./services/ssp-b:/workspace
      - ssp_b_node_modules:/workspace/node_modules
    networks:
      - adnetwork
    
  ssp-c:
    image: gcr.io/privacy-sandbox-demos/ssp-c:latest
    build: ./services/ssp-c
    container_name: "sandcastle_ssp_c"
    hostname: ${SSP_C_HOST:?err}
    env_file:
      - .env
    volumes:
      - ./services/ssp-c:/workspace
      - ssp_c_node_modules:/workspace/node_modules
    networks:
      - adnetwork
  
  ssp-d:
    image: gcr.io/privacy-sandbox-demos/ssp-d:latest
    build: ./services/ssp-d
    container_name: "sandcastle_ssp_d"
    hostname: ${SSP_C_HOST:?err}
    env_file:
      - .env
    volumes:
      - ./services/ssp-d:/workspace
      - ssp_d_node_modules:/workspace/node_modules
    networks:
      - adnetwork

  ad-server:
    image: gcr.io/privacy-sandbox-demos/ad-server:latest
    build: ./services/ad-server
    container_name: "sandcastle_ad_server"
    hostname: ${AD_SERVER_HOST:?err}
    env_file:
      - .env
    volumes:
      - ./services/ad-server:/workspace
      - ad_server_node_modules:/workspace/node_modules
    networks:
      - adnetwork

  collector:
    image: gcr.io/privacy-sandbox-demos/collector:latest
    build: ./services/collector
    container_name: "sandcastle_collector"
    hostname: ${COLLECTOR_HOST:?err}
    env_file:
      - .env
    volumes:
      - ./services/collector:/workspace
    networks:
      - adnetwork

  topics:
    image: gcr.io/privacy-sandbox-demos/topics:latest
    build: ./services/topics
    container_name: "sandcastle_topics"
    env_file:
      - .env
    volumes:
      - ./services/topics:/workspace
      - topics_node_modules:/workspace/node_modules
    networks:
      - adnetwork

  topics-server:
    image: gcr.io/privacy-sandbox-demos/topics-server:latest
    build: ./services/topics-server
    container_name: "sandcastle_topics-server"
    hostname: ${TOPICS_SERVER_HOST:?err}
    env_file:
      - .env
    volumes:
      - ./services/topics-server:/workspace
      - topics-server_node_modules:/workspace/node_modules
    networks:
      - adnetwork

  nginx:
    image: nginx:1.22.1-alpine
    container_name: "proxy"
    volumes:
      # using env variables in nginx config
      - type: bind
        source: "./nginx/nginx.conf"
        target: "/etc/nginx/templates/default.conf.template"
      - type: bind
        source: "./nginx/cert"
        target: "/cert"
    networks:
      - adnetwork
    ports:
      - "${EXTERNAL_PORT}:443"
    env_file:
      - .env
    depends_on:
      - home
      - news
      - shop
      - travel
      - ssp
      - ssp-a
      - ssp-b
      - ssp-c
      - ssp-d
      - dsp
      - dsp-a
      - dsp-b
      - dsp-c
      - dsp-d
      - ad-server
      - collector
      - topics
      - topics-server

networks:
  adnetwork:
    name: sandcastle-network
    driver: bridge
